# Generated by Django 5.1.3 on 2024-12-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitquest", "0007_profile_body_type_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="category",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="user",
        ),
        migrations.AddField(
            model_name="plan",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight_loss", "Weight Loss"),
                    ("muscle_gain", "Muscle Gain"),
                    ("toned", "Toned and Lean"),
                    ("general_fitness", "General Fitness"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="plan",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
