# Generated by Django 5.1.3 on 2024-12-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fitquest",
            "0008_remove_plan_category_remove_plan_user_plan_body_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("toned", "Toned and Lean"),
                            ("general_fitness", "General Fitness"),
                        ],
                        max_length=50,
                    ),
                ),
                ("meal_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("calories", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritional_plans",
                        to="fitquest.plan",
                    ),
                ),
            ],
        ),
    ]
