# Generated by Django 5.1.3 on 2024-12-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitquest", "0009_nutritionalplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="training_plan",
            field=models.TextField(default="Training plan"),
        ),
    ]
