# Generated by Django 5.1.3 on 2024-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitquest", "0010_plan_training_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
