# Generated by Django 5.1.3 on 2024-12-11 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitquest", "0012_progress_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
